version: "3.7"

services:
  backend:
    image: 412530390400.dkr.ecr.ap-northeast-2.amazonaws.com/cmsn-backend:latest
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: web.access
  frontend:
    image: 412530390400.dkr.ecr.ap-northeast-2.amazonaws.com/cmsn-frontend:latest
    ports: 
      - "3000:3000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: web.access